node {
    stage 'Checkout'
    git url: 'https://github.com/asperkins/cicd_iac_example.git'
    wrap([$class: 'AnsiColorBuildWrapper', colorMapName: 'xterm']) {
        stage name: 'Plan', concurrency: 1
        //Remove the terraform state file so we always start from a clean state
        if (fileExists(".terraform/terraform.tfstate")) {
            sh "rm -rf .terraform/terraform.tfstate"
        }
        if (fileExists("status")) {
            sh "rm status"
        }
        sh "loadbalance/bin/plan.sh"
        input message: 'Apply Plan', ok: 'Apply'
       
        stage name: 'Apply', concurrency: 1
        sh "loadbalance/bin/apply.sh"      
    }
}

